=== cristobal-io/aviation-scraper/test/fixtures/airport_data.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "iata": {
        "type": "string"
      },
      "icao": {
        "type": "string"
      },
      "coordinates": {
        "type": "object",
        "required":[
        "latitude",
        "longitude"
        ],
        "properties": {
          "latitude": {
            "type": "string"
          },
          "longitude": {
            "type": "string"
          }
        }
      },
      "runway": {
        "type": "object",
        "required":[
        "direction",
        "length",
        "surface"
        ],
        "properties": {
          "direction": {
            "type": "string"
          },
          "length": {
            "type": "object",
            "minproperties": 1,
            "properties": {
              "ft": {
                "type": "integer"
              },
              "m": {
                "type": "integer"
              }
            }
          },
          "surface": {
            "type": "string"
          }
        }
      }
    },
    "required": [
      "iata",
      "icao",
      "coordinates",
      "runway"
    ]
  },
  "minItems": 1
}

=== cristobal-io/aviation-scraper/test/fixtures/airport_data.json
[{
  "iata":"abj",
  "icao": "diap",
  "coordinates":{
    "latitude": "5ยบ15'41.1\"N",
    "longitude": "003ยบ55'32.8\"W"
  },
  "runway": {
    "direction": "03/21",
    "length":{
      "ft": 9842,
      "m": 3000
    },
    "surface": "macadam"
  }
}, {
  "iata":"abj",
  "icao": "diap",
  "coordinates":{
    "latitude": "5ยบ15'41.1\"N",
    "longitude": "003ยบ55'32.8\"W"
  },
  "runway": {
    "direction": "03/21",
    "length":{
      "ft": 9842,
      "m": 3000
    },
    "surface": "macadam"
  }
}
]
